# config.yml

backend:
  name: github
  branch: carpeliam/codeforboston.org
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }
